# ============================================================
# R/morfometria_graficos_v36.R
#
# PARCHE DE CARGA PARA MORFOMETRIA
# v36: curva hipsometrica + referencias conceptuales y
#      distribucion altitudinal horizontal por area.
# ============================================================
#
# Este archivo no duplica todo morfometria.R. Lee la version base,
# sustituye unicamente las dos funciones graficas de relieve y
# evalua el modulo resultante en el mismo entorno de app.R.
# ============================================================


morph_base_file <- file.path(
  "R",
  "morfometria.R"
)


if (!file.exists(morph_base_file)) {
  stop(
    "No se encontro R/morfometria.R para aplicar el parche grafico v36."
  )
}


morph_code <- paste(
  readLines(
    morph_base_file,
    warn = FALSE,
    encoding = "UTF-8"
  ),
  collapse = "\n"
)


replace_morph_region <- function(
    code,
    start_marker,
    end_marker,
    replacement
) {

  start_pos <- regexpr(
    start_marker,
    code,
    fixed = TRUE
  )[1]

  if (start_pos < 1L) {
    stop(
      paste0(
        "No se encontro el marcador inicial del parche morfometrico: ",
        start_marker
      )
    )
  }


  tail_code <- substring(
    code,
    start_pos
  )

  end_rel <- regexpr(
    end_marker,
    tail_code,
    fixed = TRUE
  )[1]

  if (end_rel < 1L) {
    stop(
      paste0(
        "No se encontro el marcador final del parche morfometrico: ",
        end_marker
      )
    )
  }


  end_pos <- start_pos +
    end_rel -
    1L


  paste0(
    if (start_pos > 1L) {
      substr(
        code,
        1L,
        start_pos - 1L
      )
    } else {
      ""
    },
    replacement,
    substr(
      code,
      end_pos,
      nchar(code)
    )
  )
}


new_draw_hipsometrica <- paste0(
'        draw_hipsometrica_plot <- function(x) {\n',
'\n',
'          if (\n',
'            is.null(x) ||\n',
'            is.null(x$relief)\n',
'          ) {\n',
'            stop(\n',
'              "La curva hipsometrica aun no esta disponible."\n',
'            )\n',
'          }\n',
'\n',
'          z <- as.numeric(\n',
'            x$relief$elevation_sample\n',
'          )\n',
'\n',
'          z <- z[\n',
'            is.finite(z)\n',
'          ]\n',
'\n',
'          if (length(z) <= 1L) {\n',
'            stop(\n',
'              "No hay suficientes datos de elevacion."\n',
'            )\n',
'          }\n',
'\n',
'          z <- sort(\n',
'            z,\n',
'            decreasing = TRUE\n',
'          )\n',
'\n',
'          zmin <- min(\n',
'            z,\n',
'            na.rm = TRUE\n',
'          )\n',
'\n',
'          zmax <- max(\n',
'            z,\n',
'            na.rm = TRUE\n',
'          )\n',
'\n',
'          zrange <- zmax - zmin\n',
'\n',
'          if (\n',
'            !is.finite(zrange) ||\n',
'            zrange <= 0\n',
'          ) {\n',
'            stop(\n',
'              "El rango altitudinal no permite construir la curva hipsometrica."\n',
'            )\n',
'          }\n',
'\n',
'          h <- (z - zmin) / zrange\n',
'\n',
'          a <- seq(\n',
'            0,\n',
'            1,\n',
'            length.out = length(h)\n',
'          )\n',
'\n',
'          hi <- suppressWarnings(\n',
'            as.numeric(\n',
'              x$relief$hypsometric_integral\n',
'            )\n',
'          )\n',
'\n',
'          area_km2 <- if (\n',
'            !is.null(x$geom) &&\n',
'            is.finite(\n',
'              as.numeric(x$geom$area_km2)\n',
'            )\n',
'          ) {\n',
'            as.numeric(\n',
'              x$geom$area_km2\n',
'            )\n',
'          } else {\n',
'            NA_real_\n',
'          }\n',
'\n',
'          pattern_label <- if (\n',
'            is.finite(hi) && hi >= 0.60\n',
'          ) {\n',
'            "predominantemente convexo"\n',
'          } else if (\n',
'            is.finite(hi) && hi < 0.35\n',
'          ) {\n',
'            "predominantemente concavo"\n',
'          } else {\n',
'            "intermedio"\n',
'          }\n',
'\n',
'          ref_x <- seq(\n',
'            0,\n',
'            1,\n',
'            length.out = 401L\n',
'          )\n',
'\n',
'          ref_convex <- sqrt(\n',
'            pmax(\n',
'              0,\n',
'              1 - ref_x^2\n',
'            )\n',
'          )\n',
'\n',
'          ref_intermediate <- 1 - ref_x\n',
'          ref_concave <- (1 - ref_x)^2\n',
'\n',
'          old_par <- graphics::par(\n',
'            no.readonly = TRUE\n',
'          )\n',
'\n',
'          on.exit(\n',
'            graphics::par(old_par),\n',
'            add = TRUE\n',
'          )\n',
'\n',
'          graphics::par(\n',
'            mar = c(\n',
'              4.8,\n',
'              5.0,\n',
'              3.6,\n',
'              1.2\n',
'            ),\n',
'            mgp = c(\n',
'              2.7,\n',
'              0.8,\n',
'              0\n',
'            )\n',
'          )\n',
'\n',
'          title_text <- paste0(\n',
'            if (is.finite(hi)) {\n',
'              sprintf("HI = %.3f", hi)\n',
'            } else {\n',
'              "HI = NA"\n',
'            },\n',
'            if (is.finite(area_km2)) {\n',
'              paste0(\n',
'                "   |   A = ",\n',
'                sprintf("%.2f", area_km2),\n',
'                " km2"\n',
'              )\n',
'            } else {\n',
'              ""\n',
'            },\n',
'            "   |   Patron ",\n',
'            pattern_label\n',
'          )\n',
'\n',
'          graphics::plot(\n',
'            a,\n',
'            h,\n',
'            type = "n",\n',
'            xlab = "Area relativa acumulada (a/A)",\n',
'            ylab = "Altura relativa (h/H)",\n',
'            main = title_text,\n',
'            xlim = c(0, 1),\n',
'            ylim = c(0, 1),\n',
'            xaxs = "i",\n',
'            yaxs = "i"\n',
'          )\n',
'\n',
'          graphics::grid(\n',
'            col = "grey88",\n',
'            lty = 1\n',
'          )\n',
'\n',
'          graphics::lines(\n',
'            ref_x,\n',
'            ref_convex,\n',
'            col = "#EF5350",\n',
'            lty = 2,\n',
'            lwd = 1.5\n',
'          )\n',
'\n',
'          graphics::lines(\n',
'            ref_x,\n',
'            ref_intermediate,\n',
'            col = "#26A69A",\n',
'            lty = 3,\n',
'            lwd = 1.5\n',
'          )\n',
'\n',
'          graphics::lines(\n',
'            ref_x,\n',
'            ref_concave,\n',
'            col = "#43A047",\n',
'            lty = 4,\n',
'            lwd = 1.5\n',
'          )\n',
'\n',
'          graphics::lines(\n',
'            a,\n',
'            h,\n',
'            col = "#1565C0",\n',
'            lwd = 2.8\n',
'          )\n',
'\n',
'          graphics::legend(\n',
'            "topright",\n',
'            legend = c(\n',
'              "Cuenca",\n',
'              "Convexa (juvenil, ref.)",\n',
'              "Intermedia (madura, ref.)",\n',
'              "Concava (senil, ref.)"\n',
'            ),\n',
'            col = c(\n',
'              "#1565C0",\n',
'              "#EF5350",\n',
'              "#26A69A",\n',
'              "#43A047"\n',
'            ),\n',
'            lty = c(\n',
'              1,\n',
'              2,\n',
'              3,\n',
'              4\n',
'            ),\n',
'            lwd = c(\n',
'              2.8,\n',
'              1.5,\n',
'              1.5,\n',
'              1.5\n',
'            ),\n',
'            bty = "n",\n',
'            cex = 0.82\n',
'          )\n',
'\n',
'          graphics::mtext(\n',
'            "Curvas de referencia conceptuales; no representan una edad cronologica de la cuenca.",\n',
'            side = 1,\n',
'            line = 3.7,\n',
'            adj = 0,\n',
'            cex = 0.72,\n',
'            col = "grey40"\n',
'          )\n',
'        }\n',
'\n',
'\n'
)


new_draw_hist_elevacion <- paste0(
'        draw_hist_elevacion_plot <- function(x) {\n',
'\n',
'          if (\n',
'            is.null(x) ||\n',
'            is.null(x$relief)\n',
'          ) {\n',
'            stop(\n',
'              "La distribucion altitudinal aun no esta disponible."\n',
'            )\n',
'          }\n',
'\n',
'          z <- as.numeric(\n',
'            x$relief$elevation_sample\n',
'          )\n',
'\n',
'          z <- z[\n',
'            is.finite(z)\n',
'          ]\n',
'\n',
'          if (length(z) <= 1L) {\n',
'            stop(\n',
'              "No hay suficientes datos de elevacion."\n',
'            )\n',
'          }\n',
'\n',
'          zmin <- min(\n',
'            z,\n',
'            na.rm = TRUE\n',
'          )\n',
'\n',
'          zmax <- max(\n',
'            z,\n',
'            na.rm = TRUE\n',
'          )\n',
'\n',
'          if (\n',
'            !is.finite(zmin) ||\n',
'            !is.finite(zmax) ||\n',
'            zmax <= zmin\n',
'          ) {\n',
'            stop(\n',
'              "El rango altitudinal no permite construir la distribucion."\n',
'            )\n',
'          }\n',
'\n',
'          n_bins <- 16L\n',
'\n',
'          breaks <- seq(\n',
'            zmin,\n',
'            zmax,\n',
'            length.out = n_bins + 1L\n',
'          )\n',
'\n',
'          hh <- graphics::hist(\n',
'            z,\n',
'            breaks = breaks,\n',
'            plot = FALSE,\n',
'            include.lowest = TRUE,\n',
'            right = TRUE\n',
'          )\n',
'\n',
'          total_n <- sum(\n',
'            hh$counts\n',
'          )\n',
'\n',
'          if (\n',
'            !is.finite(total_n) ||\n',
'            total_n <= 0\n',
'          ) {\n',
'            stop(\n',
'              "No hay celdas validas para la distribucion altitudinal."\n',
'            )\n',
'          }\n',
'\n',
'          pct <- 100 *\n',
'            hh$counts /\n',
'            total_n\n',
'\n',
'          xmax <- max(\n',
'            pct,\n',
'            na.rm = TRUE\n',
'          )\n',
'\n',
'          if (\n',
'            !is.finite(xmax) ||\n',
'            xmax <= 0\n',
'          ) {\n',
'            xmax <- 1\n',
'          }\n',
'\n',
'          xmax_plot <- xmax * 1.16\n',
'\n',
'          area_km2 <- if (\n',
'            !is.null(x$geom) &&\n',
'            is.finite(\n',
'              as.numeric(x$geom$area_km2)\n',
'            )\n',
'          ) {\n',
'            as.numeric(\n',
'              x$geom$area_km2\n',
'            )\n',
'          } else {\n',
'            NA_real_\n',
'          }\n',
'\n',
'          zmean <- suppressWarnings(\n',
'            as.numeric(x$relief$zmean)\n',
'          )\n',
'\n',
'          zmedian <- suppressWarnings(\n',
'            as.numeric(x$relief$zmedian)\n',
'          )\n',
'\n',
'          old_par <- graphics::par(\n',
'            no.readonly = TRUE\n',
'          )\n',
'\n',
'          on.exit(\n',
'            graphics::par(old_par),\n',
'            add = TRUE\n',
'          )\n',
'\n',
'          graphics::par(\n',
'            mar = c(\n',
'              4.8,\n',
'              5.2,\n',
'              4.0,\n',
'              1.0\n',
'            ),\n',
'            mgp = c(\n',
'              2.7,\n',
'              0.8,\n',
'              0\n',
'            )\n',
'          )\n',
'\n',
'          graphics::plot(\n',
'            NA_real_,\n',
'            NA_real_,\n',
'            type = "n",\n',
'            xlim = c(0, xmax_plot),\n',
'            ylim = c(zmin, zmax),\n',
'            xaxs = "i",\n',
'            yaxs = "i",\n',
'            xlab = "Area de la cuenca (%)",\n',
'            ylab = "Elevacion (m s.n.m.)",\n',
'            main = paste0(\n',
'              "Distribucion por clases altitudinales",\n',
'              if (is.finite(area_km2)) {\n',
'                paste0(\n',
'                  "   |   A = ",\n',
'                  sprintf("%.2f", area_km2),\n',
'                  " km2"\n',
'                )\n',
'              } else {\n',
'                ""\n',
'              }\n',
'            )\n',
'          )\n',
'\n',
'          graphics::grid(\n',
'            col = "grey90",\n',
'            lty = 1\n',
'          )\n',
'\n',
'          graphics::rect(\n',
'            xleft = 0,\n',
'            ybottom = hh$breaks[-length(hh$breaks)],\n',
'            xright = pct,\n',
'            ytop = hh$breaks[-1L],\n',
'            col = "#1E88E5",\n',
'            border = "white",\n',
'            lwd = 0.8\n',
'          )\n',
'\n',
'          if (is.finite(zmean)) {\n',
'            graphics::abline(\n',
'              h = zmean,\n',
'              col = "#C62828",\n',
'              lwd = 1.6,\n',
'              lty = 2\n',
'            )\n',
'          }\n',
'\n',
'          if (is.finite(zmedian)) {\n',
'            graphics::abline(\n',
'              h = zmedian,\n',
'              col = "#37474F",\n',
'              lwd = 1.6,\n',
'              lty = 3\n',
'            )\n',
'          }\n',
'\n',
'          if (is.finite(area_km2)) {\n',
'\n',
'            bottom_ticks <- graphics::axTicks(\n',
'              1\n',
'            )\n',
'\n',
'            bottom_ticks <- bottom_ticks[\n',
'              bottom_ticks >= 0 &\n',
'              bottom_ticks <= xmax_plot\n',
'            ]\n',
'\n',
'            graphics::axis(\n',
'              side = 3,\n',
'              at = bottom_ticks,\n',
'              labels = sprintf(\n',
'                "%.2f",\n',
'                bottom_ticks / 100 * area_km2\n',
'              ),\n',
'              cex.axis = 0.80\n',
'            )\n',
'\n',
'            graphics::mtext(\n',
'              "Area por clase (km2)",\n',
'              side = 3,\n',
'              line = 2.3,\n',
'              cex = 0.82\n',
'            )\n',
'          }\n',
'\n',
'          legend_items <- character(0)\n',
'          legend_cols <- character(0)\n',
'          legend_lty <- integer(0)\n',
'\n',
'          if (is.finite(zmean)) {\n',
'            legend_items <- c(\n',
'              legend_items,\n',
'              paste0(\n',
'                "Elevacion media: ",\n',
'                sprintf("%.0f", zmean),\n',
'                " m"\n',
'              )\n',
'            )\n',
'            legend_cols <- c(\n',
'              legend_cols,\n',
'              "#C62828"\n',
'            )\n',
'            legend_lty <- c(\n',
'              legend_lty,\n',
'              2L\n',
'            )\n',
'          }\n',
'\n',
'          if (is.finite(zmedian)) {\n',
'            legend_items <- c(\n',
'              legend_items,\n',
'              paste0(\n',
'                "Elevacion mediana: ",\n',
'                sprintf("%.0f", zmedian),\n',
'                " m"\n',
'              )\n',
'            )\n',
'            legend_cols <- c(\n',
'              legend_cols,\n',
'              "#37474F"\n',
'            )\n',
'            legend_lty <- c(\n',
'              legend_lty,\n',
'              3L\n',
'            )\n',
'          }\n',
'\n',
'          if (length(legend_items) > 0L) {\n',
'            graphics::legend(\n',
'              "topright",\n',
'              legend = legend_items,\n',
'              col = legend_cols,\n',
'              lty = legend_lty,\n',
'              lwd = 1.6,\n',
'              bty = "n",\n',
'              cex = 0.78\n',
'            )\n',
'          }\n',
'        }\n',
'\n',
'\n'
)


morph_code <- replace_morph_region(
  code = morph_code,
  start_marker = "        draw_hipsometrica_plot <- function(x) {",
  end_marker = "        draw_hist_elevacion_plot <- function(x) {",
  replacement = new_draw_hipsometrica
)


morph_code <- replace_morph_region(
  code = morph_code,
  start_marker = "        draw_hist_elevacion_plot <- function(x) {",
  end_marker = "        draw_hist_pendiente_plot <- function(x) {",
  replacement = new_draw_hist_elevacion
)


morph_connection <- textConnection(
  morph_code
)


on.exit(
  close(morph_connection),
  add = TRUE
)


source(
  morph_connection,
  local = TRUE,
  echo = FALSE,
  print.eval = FALSE,
  encoding = "UTF-8"
)
